-- Insert 20 inventory_items rows
-- Note: Triggers (inventory_items_metadata_cleanup, product_slug_trigger, trg_inventory_slug_sync_*) will fire automatically

INSERT INTO public.inventory_items (
  id, tenant_id, sku, name, price_cents, stock, image_url, metadata,
  created_at, updated_at, marketing_description, image_gallery, custom_cta,
  social_links, custom_branding, custom_sections, landing_page_theme, audit_log_id,
  availability, brand, category_path, directory_category_id, condition, currency,
  description, eligibility_reason, gtin, item_status, location_id, merchant_name,
  mpn, price, quantity, search_tsv, sync_status, synced_at, title, visibility,
  manufacturer, source, enrichment_status, enriched_at, enriched_by,
  enriched_from_barcode, missing_images, missing_description, missing_specs,
  missing_brand, sale_price_cents, payment_gateway_type, payment_gateway_id,
  product_type, digital_delivery_method, digital_assets, access_duration_days,
  download_limit, license_type, has_variants, is_featured, featured_at,
  featured_until, featured_priority, featured_type, product_slug,
  download_page_id, seo_title, seo_description, seo_keywords,
  enhanced_description, tags, video_url, video_thumbnail, features,
  specifications, allow_backorder, track_inventory, low_stock_threshold
) VALUES
-- Row 1
(
  'pid-PZQG-2yonj0fd', 'tid-jcvzufq2', 'R4KG-PHYS-SHIP-PUBL-QZKB',
  'Birds Eye Steamfresh Broccoli Florets, 5 oz Plus', 229, 106,
  'https://nbwsiobosqawrugnqddo.supabase.co/storage/v1/object/public/photos/t-m11e6ur7/products/i-4thay43d/original-1765232859130.jpg',
  '{"variantMedia": {"cloningStrategy": "clone_all", "parentImagesToClone": [], "variantSpecificImages": {}}, "variantConfig": {"attributeTypes": ["size", "color"], "cloningEnabled": false, "individualPhotos": false}, "featuringOptions": {"isFeatured": false, "autoFeature": false, "featuredTypes": ["store_selection"], "featuredDuration": 30, "featuredPriority": 0}, "inventorySettings": {"reorderPoint": 10, "maxStockLevel": 1000, "allowBackorder": false, "trackInventory": true, "lowStockThreshold": 5}, "publishingOptions": {"createPromotion": false, "notifyCustomers": false, "publishVariants": "all", "publishImmediately": false}, "organizationSettings": {"featured": false, "priority": 0, "searchable": true, "visibility": "public"}}'::jsonb,
  '2026-05-03 11:52:31.955', '2026-05-12 06:05:26.756',
  NULL, ARRAY[]::text[], NULL, NULL, NULL, ARRAY[]::jsonb[], 'default', NULL,
  'in_stock', 'Birds Eye', ARRAY['frozen-foods'], 'scid-tid-jcvzufq2-l1484v',
  'brand_new', 'USD', 'Fresh frozen broccoli florets, perfect for a quick and healthy side.',
  NULL, NULL, 'active', NULL, NULL, NULL, '2.29', NULL, NULL, 'pending', NULL,
  'Birds Eye Steamfresh Broccoli Florets, 5 oz Plus', 'public', NULL, 'MANUAL',
  'COMPLETE', NULL, NULL, NULL, false, false, false, false, NULL, NULL, NULL,
  'physical', 'direct_download', '[]'::jsonb, NULL, NULL, 'personal', true, false,
  NULL, NULL, 0, 'store_selection',
  'lpc_R4KG-PHYS-SHIP-PUBL-QZKB_frozen-foods_pid-PZQG-2yonj0fd_10bdd80a',
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
  false, true, 5
),
-- Row 2
(
  'pid-ULCW-79au4s1v', 'tid-m8ijkrnk', 'ULCW-PHYS-SHIP-PUBL-AHUQ',
  'Product Name - Custom attribute test', 0, 121, NULL,
  '{"variantMedia": {"cloningStrategy": "clone_all", "parentImagesToClone": [], "variantSpecificImages": {}}, "variantConfig": {"attributeTypes": ["size", "media_type"], "cloningEnabled": false, "individualPhotos": false}, "featuringOptions": {"isFeatured": false, "autoFeature": false, "featuredTypes": [], "featuredDuration": 30, "featuredPriority": 0}, "inventorySettings": {"reorderPoint": 10, "maxStockLevel": 1000, "allowBackorder": false, "trackInventory": false, "lowStockThreshold": 5}, "publishingOptions": {"createPromotion": false, "notifyCustomers": false, "publishVariants": "all", "publishImmediately": false}, "organizationSettings": {"featured": false, "priority": 0, "searchable": true, "visibility": "public"}}'::jsonb,
  '2026-05-13 16:10:56.629', '2026-05-13 16:10:56.626',
  'Test - Enhanced DescriptionEnhanced DescriptionEnhanced DescriptionEnhanced DescriptionEnhanced DescriptionEnhanced DescriptionEnhanced DescriptionEnhanced DescriptionEnhanced DescriptionEnhanced DescriptionEnhanced DescriptionEnhanced DescriptionEnhanced DescriptionEnhanced DescriptionEnhanced DescriptionEnhanced DescriptionEnhanced DescriptionEnhanced Description',
  ARRAY[]::text[], NULL, NULL, NULL, ARRAY[]::jsonb[], 'default', NULL,
  'out_of_stock', 'Product Brant Test', ARRAY['clothing'], 'scid-tid-m8ijkrnk-m51zjc',
  'brand_new', 'USD', 'Test - Product Description Product DescriptionProduct DescriptionProduct DescriptionProduct DescriptionProduct DescriptionProduct DescriptionProduct DescriptionProduct DescriptionProduct DescriptionProduct DescriptionProduct DescriptionProduct DescriptionProduct Description',
  NULL, NULL, 'active', NULL, NULL, 'Test - MPN (Manufacturer Part Number)', '0.00', NULL, NULL, 'pending', NULL,
  'Product Name - Custom attribute test', 'public', 'Test Manufacturer (Optional)', 'MANUAL',
  'COMPLETE', NULL, NULL, NULL, false, false, false, false, NULL, NULL, NULL,
  'physical', 'direct_download', '[]'::jsonb, NULL, NULL, 'personal', true, false,
  NULL, NULL, 0, 'store_selection',
  'lpc_ULCW-PHYS-SHIP-PUBL-AHUQ_clothing_pid-ULCW-79au4s1v_ec424367',
  NULL, NULL, NULL, ARRAY[]::text[], NULL, NULL, NULL, NULL, NULL, NULL,
  false, true, 5
),
-- Row 3
(
  'pid-digital-variants-001', 'tid-r6cccpag', 'DIGITAL-VARIANT-001',
  'Digital Product with Variants', 2999, 100,
  'https://example.com/product-image.jpg', NULL,
  '2026-05-14 15:42:26.493', '2026-05-14 15:42:26.493',
  'Test product for variant-specific downloads',
  ARRAY['https://example.com/image1.jpg', 'https://example.com/image2.jpg'],
  NULL, NULL, NULL, ARRAY[]::jsonb[], 'default', NULL,
  'in_stock', 'Test Brand', ARRAY['Digital Products'], NULL,
  'brand_new', 'USD', 'A digital product that has multiple variants',
  NULL, NULL, 'active', NULL, NULL, NULL, '29.99', NULL, NULL, 'pending', NULL,
  'Digital Product with Variants', 'public', 'Test Manufacturer', 'MANUAL',
  'COMPLETE', NULL, NULL, NULL, false, false, false, false, NULL, NULL, NULL,
  'digital', 'direct_download', NULL, NULL, NULL, NULL, true, false,
  NULL, NULL, 0, 'store_selection',
  'lpc_DIGITAL-VARIANT-001_digital-products_pid-digital-variants-001_4028e119',
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
  false, true, 5
),
-- Row 4
(
  'sid-jw2g3ftw', 'tid-m8ijkrnk', 'qsid-1767098488111',
  'Levi''s 511 Slim Fit Jeans - Men''s 32x32', 1299, 6,
  'https://nbwsiobosqawrugnqddo.supabase.co/storage/v1/object/public/photos/t-ucgs9idl/products/iid-4eosklt0/original-1765615419382.jpg',
  NULL, '2025-12-30 12:45:09.333', '2026-03-23 16:54:00.766',
  NULL, ARRAY[]::text[], NULL, NULL, NULL, ARRAY[]::jsonb[], 'default', NULL,
  'in_stock', 'Levi''s', ARRAY['clothing'], 'scid-tid-m8ijkrnk-m51zjc',
  'brand_new', 'USD', 'A modern slim with room to move, the 511 Slim Fit Jeans are a classic since right now.',
  NULL, NULL, 'active', NULL, NULL, NULL, '12.99', NULL, NULL, 'pending', NULL,
  'Levi''s 511 Slim Fit Jeans - Men''s 32x32', 'public', NULL, 'MANUAL',
  'COMPLETE', NULL, NULL, NULL, false, false, false, false, NULL, NULL, NULL,
  'physical', NULL, NULL, NULL, NULL, NULL, true, false,
  NULL, NULL, 0, 'seasonal',
  'lpc_qsid-1767098488111_clothing_sid-jw2g3ftw_2c5aeeae',
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
  false, true, 5
),
-- Row 5
(
  'sid-8xq20uyv', 'tid-zcp9a56y', '3GYK-PHYS-SHIP-PUBL-EZZG',
  'Neutrogena Hydro Boost Water Gel, 50g', 1999, 57,
  'https://nbwsiobosqawrugnqddo.supabase.co/storage/v1/object/public/photos/tid-c2r2kf8v/products/sid-yawb6e5h/original-1766438595493.jpg',
  NULL, '2026-04-02 07:22:28.279', '2026-04-02 08:35:41.131',
  NULL, ARRAY[]::text[], NULL, NULL, NULL, ARRAY[]::jsonb[], 'default', NULL,
  'in_stock', 'Neutrogena', ARRAY['personal-care'], 'tid-zcp9a56y_personal-care',
  'brand_new', 'USD', 'A hydrating water-gel moisturizer that provides intense hydration for supple and smooth skin.',
  NULL, NULL, 'active', NULL, NULL, NULL, '19.99', NULL, NULL, 'pending', NULL,
  'Neutrogena Hydro Boost Water Gel, 50g', 'public', NULL, 'MANUAL',
  'COMPLETE', NULL, NULL, NULL, false, false, false, false, NULL, NULL, NULL,
  'physical', NULL, NULL, NULL, NULL, NULL, true, false,
  NULL, NULL, 0, 'store_selection',
  'lpc_3GYK-PHYS-SHIP-PUBL-EZZG_personal-care_sid-8xq20uyv_db4cf619',
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
  false, true, 5
),
-- Row 6
(
  'pid-R4KG-qz3cfdvr', 'tid-042hi7ju', 'R4KG-PHYS-SHIP-PUBL-QZKB',
  'Birds Eye Steamfresh Broccoli Florets, 5 oz Plus', 229, 6,
  'https://nbwsiobosqawrugnqddo.supabase.co/storage/v1/object/public/photos/t-m11e6ur7/products/i-4thay43d/original-1765232859130.jpg',
  NULL, '2026-05-02 22:32:01.653', '2026-05-02 22:36:21.262',
  NULL, ARRAY[]::text[], NULL, NULL, NULL, ARRAY[]::jsonb[], 'default', NULL,
  'in_stock', 'Birds Eye', ARRAY['frozen-foods'], 'scid-tid-042hi7ju-wf8tw3',
  'brand_new', 'USD', 'Fresh frozen broccoli florets, perfect for a quick and healthy side.',
  NULL, NULL, 'active', NULL, NULL, NULL, '2.29', NULL, NULL, 'pending', NULL,
  'Birds Eye Steamfresh Broccoli Florets, 10.8 oz Plus', 'public', NULL, 'MANUAL',
  'COMPLETE', NULL, NULL, NULL, false, false, false, false, NULL, NULL, NULL,
  'physical', NULL, NULL, NULL, NULL, NULL, true, false,
  NULL, NULL, 0, 'store_selection',
  'lpc_R4KG-PHYS-SHIP-PUBL-QZKB_frozen-foods_pid-R4KG-qz3cfdvr_10bdd80a',
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
  false, true, 5
),
-- Row 7
(
  'sid-hmgqmgpn', 'tid-zcp9a56y', '3GYK-PHYS-SHIP-PUBL-9MJR',
  'GentleCare Hypoallergenic Baby Wipes, 80 Count', 499, 9,
  'https://nbwsiobosqawrugnqddo.supabase.co/storage/v1/object/public/photos/t-ccu0mh28/products/sid-lm1jpw23/original-1765714753660.jpg',
  NULL, '2026-04-02 07:22:28.622', '2026-04-02 08:18:39.982',
  NULL, ARRAY[]::text[], NULL, NULL, NULL, ARRAY[]::jsonb[], 'default', NULL,
  'in_stock', 'GentleCare', ARRAY['baby-care'], 'tid-zcp9a56y_baby-care',
  'brand_new', 'USD', 'Soft and gentle hypoallergenic baby wipes for sensitive skin.',
  NULL, NULL, 'active', NULL, NULL, NULL, '4.99', NULL, NULL, 'pending', NULL,
  'GentleCare Hypoallergenic Baby Wipes, 80 Count', 'public', NULL, 'MANUAL',
  'COMPLETE', NULL, NULL, NULL, false, false, false, false, NULL, NULL, NULL,
  'physical', NULL, NULL, NULL, NULL, NULL, true, false,
  NULL, NULL, 0, 'store_selection',
  'lpc_3GYK-PHYS-SHIP-PUBL-9MJR_baby-care_sid-hmgqmgpn_5aadd1d4',
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
  false, true, 5
),
-- Row 8
(
  'sid-ktrl9y7m', 'tid-8622qs2t', 'qsid-1766436467819',
  'Birds Eye Steamfresh Broccoli Florets, 10.8 oz', 229, 10,
  'https://nbwsiobosqawrugnqddo.supabase.co/storage/v1/object/public/photos/t-m11e6ur7/products/i-4thay43d/original-1765232859130.jpg',
  NULL, '2026-03-26 01:25:08.076', '2026-05-02 21:42:42.74',
  NULL, ARRAY[]::text[], NULL, NULL, NULL, ARRAY[]::jsonb[], 'default', NULL,
  'in_stock', 'Birds Eye', ARRAY['frozen-foods'], 'scid-tid-8622qs2t-mxfijm',
  'brand_new', 'USD', 'Fresh frozen broccoli florets, perfect for a quick and healthy side.',
  NULL, NULL, 'active', NULL, NULL, NULL, '2.29', NULL, NULL, 'pending', NULL,
  'Birds Eye Steamfresh Broccoli Florets, 10.8 oz', 'public', NULL, 'MANUAL',
  'COMPLETE', NULL, NULL, NULL, false, false, false, false, NULL, NULL, NULL,
  'physical', NULL, NULL, NULL, NULL, NULL, true, false,
  NULL, NULL, 0, 'store_selection',
  'lpc_qsid-1766436467819_frozen-foods_sid-ktrl9y7m_297ea197',
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
  false, true, 5
),
-- Row 9
(
  'sid-czxkkwyc', 'tid-zcp9a56y', '3GYK-PHYS-SHIP-PUBL-VT89',
  'GentleCare Hypoallergenic Baby Wipes, 80 ct', 299, 72,
  'https://nbwsiobosqawrugnqddo.supabase.co/storage/v1/object/public/photos/tid-c2r2kf8v/products/sid-5ms4g1ui/original-1766438615929.jpg',
  NULL, '2026-04-02 07:22:29.329', '2026-04-02 07:26:58.623',
  NULL, ARRAY[]::text[], NULL, NULL, NULL, ARRAY[]::jsonb[], 'default', NULL,
  'in_stock', 'GentleCare', ARRAY['baby-care'], 'tid-zcp9a56y_baby-care',
  'brand_new', 'USD', 'Ultra-soft, hypoallergenic baby wipes for sensitive skin.',
  NULL, NULL, 'active', NULL, NULL, NULL, '2.99', NULL, NULL, 'pending', NULL,
  'GentleCare Hypoallergenic Baby Wipes, 80 ct', 'public', NULL, 'MANUAL',
  'COMPLETE', NULL, NULL, NULL, false, false, false, false, NULL, NULL, NULL,
  'physical', NULL, NULL, NULL, NULL, NULL, true, false,
  NULL, NULL, 0, 'store_selection',
  'lpc_3GYK-PHYS-SHIP-PUBL-VT89_baby-care_sid-czxkkwyc_b3a25cd1',
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
  false, true, 5
),
-- Row 10
(
  'sid-zpw3rbxj', 'tid-042hi7ju', 'qsid-1766436467819',
  'Birds Eye Steamfresh Broccoli Florets, 10.8 oz', 229, 10,
  'https://nbwsiobosqawrugnqddo.supabase.co/storage/v1/object/public/photos/t-m11e6ur7/products/i-4thay43d/original-1765232859130.jpg',
  NULL, '2026-03-26 01:33:58.077', '2026-05-02 22:01:32.623',
  NULL, ARRAY[]::text[], NULL, NULL, NULL, ARRAY[]::jsonb[], 'default', NULL,
  'in_stock', 'Birds Eye', ARRAY['frozen-foods'], 'scid-tid-042hi7ju-wf8tw3',
  'brand_new', 'USD', 'Fresh frozen broccoli florets, perfect for a quick and healthy side.',
  NULL, NULL, 'active', NULL, NULL, NULL, '2.29', NULL, NULL, 'pending', NULL,
  'Birds Eye Steamfresh Broccoli Florets, 10.8 oz', 'public', NULL, 'MANUAL',
  'COMPLETE', NULL, NULL, NULL, false, false, false, false, NULL, NULL, NULL,
  'physical', NULL, NULL, NULL, NULL, NULL, true, false,
  NULL, NULL, 0, 'store_selection',
  'lpc_qsid-1766436467819_frozen-foods_sid-zpw3rbxj_297ea197',
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
  false, true, 5
),
-- Row 11
(
  'sid-qiazuxmt', 'tid-m8ijkrnk', 'qsid-1767098488110',
  'Calvin Klein Cotton Stretch Shirt, Size L', 6999, 21,
  'https://nbwsiobosqawrugnqddo.supabase.co/storage/v1/object/public/photos/t-ucgs9idl/products/iid-ky96bhtl/original-1765615394842.jpg',
  NULL, '2025-12-30 12:45:08.693', '2026-03-23 16:27:51.501',
  NULL, ARRAY[]::text[], NULL, NULL, NULL, ARRAY[]::jsonb[], 'default', NULL,
  'in_stock', 'Calvin Klein', ARRAY['mens-shirts'], 'tid-m8ijkrnk_mens-shirts',
  'brand_new', 'USD', 'A sleek, comfortable stretch shirt perfect for any occasion.',
  NULL, NULL, 'active', NULL, NULL, NULL, '69.99', NULL, NULL, 'pending', NULL,
  'Calvin Klein Cotton Stretch Shirt, Size L', 'public', NULL, 'MANUAL',
  'COMPLETE', NULL, NULL, NULL, false, false, false, false, NULL, NULL, NULL,
  'physical', NULL, NULL, NULL, NULL, NULL, true, true,
  '2026-01-20 05:37:26.418', NULL, 50, 'sale',
  'lpc_qsid-1767098488110_mens-shirts_sid-qiazuxmt_43b41177',
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
  false, true, 5
),
-- Row 12
(
  'pid-AVR6-2ghjil3x', 'tid-8622qs2t', 'R4KG-PHYS-SHIP-PUBL-QZKB',
  'Birds Eye Steamfresh Broccoli Florets, 5 oz Plus', 229, 6,
  'https://nbwsiobosqawrugnqddo.supabase.co/storage/v1/object/public/photos/t-m11e6ur7/products/i-4thay43d/original-1765232859130.jpg',
  NULL, '2026-05-02 22:36:54.338', '2026-05-02 22:36:54.334',
  NULL, ARRAY[]::text[], NULL, NULL, NULL, ARRAY[]::jsonb[], 'default', NULL,
  'in_stock', 'Birds Eye', ARRAY['frozen-foods'], 'scid-tid-8622qs2t-mxfijm',
  'brand_new', 'USD', 'Fresh frozen broccoli florets, perfect for a quick and healthy side.',
  NULL, NULL, 'active', NULL, NULL, NULL, '2.29', NULL, NULL, 'pending', NULL,
  'Birds Eye Steamfresh Broccoli Florets, 10.8 oz Plus', 'public', NULL, 'MANUAL',
  'COMPLETE', NULL, NULL, NULL, false, false, false, false, NULL, NULL, NULL,
  'physical', NULL, NULL, NULL, NULL, NULL, true, false,
  NULL, NULL, 0, 'store_selection',
  'lpc_R4KG-PHYS-SHIP-PUBL-QZKB_frozen-foods_pid-AVR6-2ghjil3x_10bdd80a',
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
  false, true, 5
),
-- Row 13
(
  'sid-2vnwdcfa', 'tid-zcp9a56y', '3GYK-PHYS-SHIP-PUBL-YKHK',
  'Nature''s Bounty Biotin 10000 mcg, 120 Softgels', 1499, 12,
  'https://nbwsiobosqawrugnqddo.supabase.co/storage/v1/object/public/photos/t-ccu0mh28/products/sid-btf8hysk/original-1765714697365.jpg',
  NULL, '2026-04-02 07:22:26.558', '2026-04-02 09:01:02.506',
  NULL, ARRAY[]::text[], NULL, NULL, NULL, ARRAY[]::jsonb[], 'default', NULL,
  'in_stock', 'Nature''s Bounty', ARRAY['vitamins-supplements'], 'tid-zcp9a56y_vitamins-supplements',
  'brand_new', 'USD', 'Supports healthy hair, skin, and nails with a high potency biotin supplement.',
  NULL, NULL, 'active', NULL, NULL, NULL, '14.99', NULL, NULL, 'pending', NULL,
  'Nature''s Bounty Biotin 10000 mcg, 120 Softgels', 'public', NULL, 'MANUAL',
  'COMPLETE', NULL, NULL, NULL, false, false, false, false, NULL, NULL, NULL,
  'physical', NULL, NULL, NULL, NULL, NULL, true, false,
  NULL, NULL, 0, 'store_selection',
  'lpc_3GYK-PHYS-SHIP-PUBL-YKHK_vitamins-supplements_sid-2vnwdcfa_c0bfc59c',
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
  false, true, 5
),
-- Row 14
(
  'sid-zfotsnyq', 'tid-zcp9a56y', '3GYK-PHYS-SHIP-PUBL-52EC',
  'Cetaphil Gentle Skin Cleanser, 16 fl oz', 1399, 8,
  'https://nbwsiobosqawrugnqddo.supabase.co/storage/v1/object/public/photos/t-ccu0mh28/products/sid-crxq4iol/original-1765714734138.jpg',
  NULL, '2026-04-02 07:22:27.94', '2026-04-02 08:51:56.769',
  NULL, ARRAY[]::text[], NULL, NULL, NULL, ARRAY[]::jsonb[], 'default', NULL,
  'in_stock', 'Cetaphil', ARRAY['personal-care'], 'tid-zcp9a56y_personal-care',
  'brand_new', 'USD', 'A mild, soap-free face and body cleanser that hydrates and soothes skin as it cleans.',
  NULL, NULL, 'active', NULL, NULL, NULL, '13.99', NULL, NULL, 'pending', NULL,
  'Cetaphil Gentle Skin Cleanser, 16 fl oz', 'public', NULL, 'MANUAL',
  'COMPLETE', NULL, NULL, NULL, false, false, false, false, NULL, NULL, NULL,
  'physical', NULL, NULL, NULL, NULL, NULL, true, false,
  NULL, NULL, 0, 'store_selection',
  'lpc_3GYK-PHYS-SHIP-PUBL-52EC_personal-care_sid-zfotsnyq_1e9ba732',
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
  false, true, 5
),
-- Row 15
(
  'sid-82lhweps', 'tid-zcp9a56y', '3GYK-PHYS-SHIP-PUBL-CMMJ',
  'Nature''s Bounty Vitamin D3 1000 IU, 250 Softgels', 1499, 7,
  'https://nbwsiobosqawrugnqddo.supabase.co/storage/v1/object/public/photos/tid-c2r2kf8v/products/sid-axugi4r6/original-1766438560194.jpg',
  NULL, '2026-04-02 07:22:26.905', '2026-04-02 08:49:50.789',
  NULL, ARRAY[]::text[], NULL, NULL, NULL, ARRAY[]::jsonb[], 'default', NULL,
  'in_stock', 'Nature''s Bounty', ARRAY['vitamins-supplements'], 'tid-zcp9a56y_vitamins-supplements',
  'brand_new', 'USD', 'Vitamin D3 supplement that supports immune health, bone health, and calcium absorption.',
  NULL, NULL, 'active', NULL, NULL, NULL, '14.99', NULL, NULL, 'pending', NULL,
  'Nature''s Bounty Vitamin D3 1000 IU, 250 Softgels', 'public', NULL, 'MANUAL',
  'COMPLETE', NULL, NULL, NULL, false, false, false, false, NULL, NULL, NULL,
  'physical', NULL, NULL, NULL, NULL, NULL, true, false,
  NULL, NULL, 0, 'store_selection',
  'lpc_3GYK-PHYS-SHIP-PUBL-CMMJ_vitamins-supplements_sid-82lhweps_9acb8fba',
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
  false, true, 5
),
-- Row 16 (has features, enhanced_description)
(
  'pid-3pgmh1mv', 'tid-8622qs2t', 'R4KG-PHYS-SHIP-PUBL-3ZF6',
  'Checkers Vanilla Custard', 799, 5,
  'https://nbwsiobosqawrugnqddo.supabase.co/storage/v1/object/public/photos/tid-042hi7ju/R4KG-PHYS-SHIP-PUBL-3ZF6/1774603020403.png',
  NULL, '2026-05-01 21:44:54.312', '2026-05-02 13:53:41.628',
  NULL, ARRAY[]::text[], NULL, NULL, NULL, ARRAY[]::jsonb[], 'default', NULL,
  'in_stock', 'Checkers', ARRAY['seasonings-and-spices'], 'cat-AVR6-dozxuh',
  'brand_new', 'USD', 'Delight in the smooth, aromatic flavor of Checkers Vanilla Custard, a premium custard powder that blends effortlessly with milk to create creamy, velvety desserts. Perfect for families, bakers, and dessert lovers alike.',
  NULL, NULL, 'active', NULL, NULL, NULL, '7.99', NULL, NULL, 'pending', NULL,
  'Checkers Vanilla Custard', 'public', 'Checkers', 'MANUAL',
  'COMPLETE', NULL, NULL, NULL, false, false, false, false, NULL, NULL, NULL,
  'physical', NULL, NULL, NULL, NULL, NULL, true, false,
  NULL, NULL, 0, 'store_selection',
  'lpc_R4KG-PHYS-SHIP-PUBL-3ZF6_seasonings-and-spices_pid-3pgmh1mv_0bd557e3',
  NULL, NULL, NULL, NULL,
  'Rich Vanilla Flavor for Every Dessert\nCheckers Vanilla Custard delivers a classic vanilla aroma and a luscious texture that enhances puddings, pies, and layered desserts.',
  NULL, NULL, NULL,
  ARRAY['Versatile for Sweet Creations', 'Ideal for custard desserts, pies, trifles, and puddings', 'Perfect for warm or chilled servings', 'Enhances cakes, pastries, and fruit toppings', 'Easy to prepare for everyday or special occasions'],
  NULL, false, true, 5
),
-- Row 17 (has features, enhanced_description)
(
  'sid-xeabktla', 'tid-042hi7ju', 'R4KG-PHYS-SHIP-PUBL-3ZF6',
  'Checkers Vanilla Custard', 799, 5,
  'https://nbwsiobosqawrugnqddo.supabase.co/storage/v1/object/public/photos/tid-042hi7ju/R4KG-PHYS-SHIP-PUBL-3ZF6/1774603020403.png',
  NULL, '2026-03-27 08:40:14.713', '2026-03-27 10:16:36.745',
  NULL, ARRAY[]::text[], NULL, NULL, NULL, ARRAY[]::jsonb[], 'default', NULL,
  'in_stock', 'Checkers', ARRAY['seasonings-and-spices'], 'scid-tid-042hi7ju-c3ww1h',
  'brand_new', 'USD', 'Delight in the smooth, aromatic flavor of Checkers Vanilla Custard, a premium custard powder that blends effortlessly with milk to create creamy, velvety desserts. Perfect for families, bakers, and dessert lovers alike.',
  NULL, NULL, 'active', NULL, NULL, NULL, '7.99', NULL, NULL, 'pending', NULL,
  'Checkers Vanilla Custard', 'public', 'Checkers', 'MANUAL',
  'COMPLETE', NULL, NULL, NULL, false, false, false, false, NULL, NULL, NULL,
  'physical', NULL, NULL, NULL, NULL, NULL, true, false,
  NULL, NULL, 0, 'store_selection',
  'lpc_R4KG-PHYS-SHIP-PUBL-3ZF6_seasonings-and-spices_sid-xeabktla_0bd557e3',
  NULL, NULL, NULL, NULL,
  'Rich Vanilla Flavor for Every Dessert\nCheckers Vanilla Custard delivers a classic vanilla aroma and a luscious texture that enhances puddings, pies, and layered desserts.',
  NULL, NULL, NULL,
  ARRAY['Versatile for Sweet Creations', 'Ideal for custard desserts, pies, trifles, and puddings', 'Perfect for warm or chilled servings', 'Enhances cakes, pastries, and fruit toppings', 'Easy to prepare for everyday or special occasions'],
  NULL, false, true, 5
),
-- Row 18 (has features, enhanced_description, specifications)
(
  'sid-7xsn12ae', 'tid-8622qs2t', 'qsid-1766436571328',
  'Galactic Quest Laser Tag 2-Player Set', 3499, 11,
  'https://nbwsiobosqawrugnqddo.supabase.co/storage/v1/object/public/photos/t-v84j50g0/products/i-6la5jgvm/original-1765116087133.jpg',
  NULL, '2026-03-26 01:25:15.642', '2026-05-02 21:32:33.882',
  NULL, ARRAY[]::text[], NULL, NULL, NULL, ARRAY[]::jsonb[], 'default', NULL,
  'in_stock', 'LaserX', ARRAY['toys-games'], 'scid-tid-8622qs2t-1sm1xk',
  'brand_new', 'USD', 'A thrilling laser tag set for two players, perfect for dynamic indoor and outdoor play.',
  NULL, NULL, 'active', NULL, NULL, NULL, '34.99', NULL, NULL, 'pending', NULL,
  'Galactic Quest Laser Tag 2-Player Set', 'public', NULL, 'MANUAL',
  'COMPLETE', NULL, NULL, NULL, false, false, false, false, NULL, NULL, NULL,
  'physical', NULL, NULL, NULL, NULL, NULL, true, false,
  NULL, NULL, 0, 'store_selection',
  'lpc_qsid-1766436571328_toys-games_sid-7xsn12ae_71a3471a',
  NULL, NULL, NULL, NULL,
  'Introducing the ultimate Laser Tag experience with the Galactic Quest 2-Player Set by LaserX. Transform your home or backyard into a laser tag arena and engage in epic battles with friends and family. This set comes with two high-quality laser blasters and matching vests, each equipped with hit sensors and interactive lights and sounds to make your laser tag games more exciting and immersive than ever before. The blasters feature multiple shooting modes, giving players the ability to strategize and adapt in the heat of battle. Whether you''re looking for a fun way to keep the kids active or a competitive game for parties, the Galactic Quest Laser Tag Set promises hours of fun for everyone.',
  NULL, NULL, NULL,
  ARRAY['Two high-quality laser blasters with matching vests for immersive play', 'Interactive lights and sounds for real-time battle feedback', 'Multiple shooting modes for strategic gameplay', 'Wide range allows for exciting play in large indoor spaces or outdoors', 'Perfect for kids, teens, and adults looking to add excitement to any gathering'],
  '{"size": "One Size Fits Most", "color": "Red and Blue", "range": "Up to 200 feet", "quantity": "2 Blasters and 2 Vests", "batteryType": "AA", "batteryQuantity": "6 (not included)", "batteryRequired": true}'::jsonb,
  false, true, 5
),
-- Row 19 (has features, enhanced_description, specifications)
(
  'sid-tjphaqcd', 'tid-zcp9a56y', '3GYK-PHYS-SHIP-PUBL-EMR9',
  'Tylenol Extra Strength Caplets, 100 Count', 1099, 10,
  'https://nbwsiobosqawrugnqddo.supabase.co/storage/v1/object/public/photos/tid-c2r2kf8v/products/sid-bboy1cd6/original-1766438539341.jpg',
  NULL, '2026-04-02 07:22:25.276', '2026-04-02 19:37:54.932',
  NULL, ARRAY[]::text[], NULL, NULL, NULL, ARRAY[]::jsonb[], 'default', NULL,
  'in_stock', 'Tylenol', ARRAY['otc-medicine'], 'tid-zcp9a56y_otc-medicine',
  'brand_new', 'USD', 'Tylenol Extra Strength caplets provide temporary relief of minor aches and pains and help reduce fever.',
  NULL, NULL, 'active', NULL, NULL, NULL, '10.99', NULL, NULL, 'pending', NULL,
  'Tylenol Extra Strength Caplets, 100 Count', 'public', NULL, 'MANUAL',
  'COMPLETE', NULL, NULL, NULL, false, false, false, false, NULL, NULL, NULL,
  'physical', NULL, NULL, NULL, NULL, NULL, true, false,
  NULL, NULL, 0, 'store_selection',
  'lpc_3GYK-PHYS-SHIP-PUBL-EMR9_otc-medicine_sid-tjphaqcd_d804541b',
  NULL, NULL, NULL, NULL,
  'Experience effective relief with Tylenol Extra Strength Caplets, designed to alleviate minor aches, pains, and fever, allowing you to move through your day more comfortably. Each caplet contains 500 mg of acetaminophen, a trusted pain reliever and fever reducer. Perfect for adults and children 12 years and older, Tylenol Extra Strength is gentle on your stomach, but tough on pain. Whether you''re battling a backache, minor arthritis pain, toothache, menstrual cramps, or a high fever, Tylenol Extra Strength is your go-to solution. The convenient 100 count bottle ensures you have enough to last you through the cold season, post-exercise soreness, or occasional headaches. Tylenol is the #1 doctor recommended brand for pain relief and fever reduction, making it a trusted companion in any medicine cabinet.',
  NULL, NULL, NULL,
  ARRAY['Contains 500 mg of acetaminophen per caplet', 'Provides temporary relief of minor aches and pains and helps reduce fever', 'Gentle on the stomach', 'Recommended by doctors', 'Comes in a convenient 100 count bottle'],
  '{"size": "100 Count", "quantity": "100 Caplets", "dosageForm": "Caplet", "ingredients": "Active ingredient (in each caplet): Acetaminophen 500 mg", "recommendedAge": "12 years and older"}'::jsonb,
  false, true, 5
),
-- Row 20 (has features, enhanced_description, specifications)
(
  'sid-6ktioup0', 'tid-042hi7ju', 'qsid-1766436571328',
  'Galactic Quest Laser Tag 2-Player Set', 3499, 11,
  'https://nbwsiobosqawrugnqddo.supabase.co/storage/v1/object/public/photos/t-v84j50g0/products/i-6la5jgvm/original-1765116087133.jpg',
  NULL, '2026-03-26 01:33:59.82', '2026-05-02 21:34:01.878',
  NULL, ARRAY[]::text[], NULL, NULL, NULL, ARRAY[]::jsonb[], 'default', NULL,
  'in_stock', 'LaserX', ARRAY['toys-games'], 'scid-tid-042hi7ju-0biqxp',
  'brand_new', 'USD', 'A thrilling laser tag set for two players, perfect for dynamic indoor and outdoor play.',
  NULL, NULL, 'active', NULL, NULL, NULL, '34.99', NULL, NULL, 'pending', NULL,
  'Galactic Quest Laser Tag 2-Player Set', 'public', NULL, 'MANUAL',
  'COMPLETE', NULL, NULL, NULL, false, false, false, false, NULL, NULL, NULL,
  'physical', NULL, NULL, NULL, NULL, NULL, true, false,
  NULL, NULL, 0, 'store_selection',
  'lpc_qsid-1766436571328_toys-games_sid-6ktioup0_71a3471a',
  NULL, NULL, NULL, NULL,
  'Introducing the ultimate Laser Tag experience with the Galactic Quest 2-Player Set by LaserX. Transform your home or backyard into a laser tag arena and engage in epic battles with friends and family. This set comes with two high-quality laser blasters and matching vests, each equipped with hit sensors and interactive lights and sounds to make your laser tag games more exciting and immersive than ever before. The blasters feature multiple shooting modes, giving players the ability to strategize and adapt in the heat of battle. Whether you''re looking for a fun way to keep the kids active or a competitive game for parties, the Galactic Quest Laser Tag Set promises hours of fun for everyone.',
  NULL, NULL, NULL,
  ARRAY['Two high-quality laser blasters with matching vests for immersive play', 'Interactive lights and sounds for real-time battle feedback', 'Multiple shooting modes for strategic gameplay', 'Wide range allows for exciting play in large indoor spaces or outdoors', 'Perfect for kids, teens, and adults looking to add excitement to any gathering'],
  '{"size": "One Size Fits Most", "color": "Red and Blue", "range": "Up to 200 feet", "quantity": "2 Blasters and 2 Vests", "batteryType": "AA", "batteryQuantity": "6 (not included)", "batteryRequired": true}'::jsonb,
  false, true, 5
)
ON CONFLICT (id) DO NOTHING;
