packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma

onlyBuiltDependencies:
  - '@newrelic/fn-inspect'
  - '@newrelic/native-metrics'
  - '@sentry/cli'
  - '@tailwindcss/oxide'
  - aws-sdk
  - protobufjs
  - sharp
  - unrs-resolver
