packages:
  - apps/*
  - packages/*

allowBuilds:
  '@google/genai': true
  '@newrelic/fn-inspect': false
  '@newrelic/native-metrics': false
  '@prisma/client': false
  '@prisma/engines': false
  '@railway/cli': false
  '@sentry/cli': false
  core-js: false
  es5-ext: false
  esbuild: false
  onnxruntime-node: true
  prisma: false
  protobufjs: false
  sharp: false
  stripe-cli: false
  unrs-resolver: false

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma

onlyBuiltDependencies:
  - '@newrelic/fn-inspect'
  - '@newrelic/native-metrics'
  - '@sentry/cli'
  - '@tailwindcss/oxide'
  - aws-sdk
  - protobufjs
  - sharp
  - unrs-resolver

patchedDependencies:
  next-themes@0.4.6: patches/next-themes@0.4.6.patch
