-- ============================================================
-- Migration 149: Marketing Ops — Recovery Management Intake
-- ============================================================
-- Description:
--   Adds the data layer for the Recovery Management Engine (BBB
--   dispute mediation, legal de-escalation, high-stakes grievance
--   recovery). Extends the existing review-centric campaign model
--   with a second campaign category track and token-gated dispute
--   intake tables — no structural rewrite, no microservice split.
--
--   1. mkt_campaigns_list.campaign_category — new column (default
--      'review_management') discriminating the review track from
--      the recovery track. Existing rows default to review_management
--      with zero backfill. The stage column (VARCHAR(50), no DB enum)
--      already accepts arbitrary string values, so the 9 recovery
--      stage literals (audit_identified, framework_preview_generated,
--      outreach_dispatched, awaiting_owner_intake, intake_submitted,
--      final_resolution_drafted, owner_approved, resolved_and_closed,
--      dead) need no schema change — they are app-layer-enforced via
--      recoveryStages.ts + a category-aware transition table in
--      MarketingCampaignService.
--
--   2. mkt_dispute_intake — one row per recovery campaign holding the
--      magic-link access token, expiry, and owner submission payload
--      (statement, proposed resolution, status flag, attachments).
--      campaign_id is UNIQUE (one intake per campaign). The token is
--      a 32-char URL-safe nanoid generated by id-generator.ts. No
--      account auth — the token IS the trust boundary (mirrors
--      mkt_deliverable_preview_tokens).
--
--   3. mkt_dispute_attachments — proof files (PDF/PNG/JPEG) attached
--      to a dispute intake submission. Storage backend is deferred to
--      the intake portal sprint (S2); this table holds the metadata
--      (file_url, file_name, file_type, file_size).
--
--   RLS: mkt_* tables do not enable row level security. The
--   /// This model contains row level security comments in
--   schema.prisma are Supabase introspection artifacts, not applied
--   policies (confirmed against migrations 141–148 — none run
--   ENABLE ROW LEVEL SECURITY). New tables follow suit so the
--   public intake route can read rows by token without auth.
--
--   updated_at: no explicit trigger function — mkt_* tables rely on
--   DEFAULT NOW() + app-layer Prisma @updatedAt, matching migrations
--   141–148.
--
-- Prerequisite: 148_marketing_ops_scorecards_scope_stage.sql applied
-- Date: 2026-08-01
-- ============================================================

-- ============================================================
-- STEP 1: Add campaign_category column to mkt_campaigns_list
-- ============================================================
-- Discriminates review track ('review_management') from recovery
-- track ('recovery_management'). Default keeps every existing row on
-- the review track with zero backfill. The category drives which
-- stage transition table MarketingCampaignService uses.

ALTER TABLE mkt_campaigns_list
  ADD COLUMN IF NOT EXISTS campaign_category VARCHAR(30)
  NOT NULL DEFAULT 'review_management';

CREATE INDEX IF NOT EXISTS idx_mkt_campaigns_campaign_category
  ON mkt_campaigns_list(campaign_category);

-- ============================================================
-- STEP 2: Dispute intake table (one row per recovery campaign)
-- ============================================================
-- Holds the magic-link token + owner submission payload. The token
-- is the trust boundary — no account auth required to submit. The
-- campaign_id UNIQUE constraint means reissue must UPDATE the
-- existing row (new token + new expiry), not INSERT a second row.

CREATE TABLE IF NOT EXISTS mkt_dispute_intake (
  id                    VARCHAR(255)  PRIMARY KEY,             -- mdint-{nanoid}
  campaign_id           VARCHAR(255)  UNIQUE NOT NULL,         -- one intake per campaign
  tenant_id             VARCHAR(255),                          -- mirrors mkt_campaigns_list.tenant_id (nullable for admin-scoped campaigns)
  access_token          VARCHAR(255)  UNIQUE NOT NULL,         -- 32-char URL-safe nanoid (the magic link token)
  expires_at            TIMESTAMPTZ   NOT NULL,                -- 7-day default, configurable via unifiedConfig
  -- Owner submission payload (NULL until the owner submits via the public form)
  owner_statement       TEXT,                                 -- "What actually happened?"
  service_date          DATE,                                 -- when the disputed service was scheduled/rendered
  proposed_resolution   TEXT,                                 -- single-select + custom text (Partial Refund, Full Refund, Re-scheduled, Enforcing Agreement)
  status_flag           VARCHAR(50),                           -- REFUND_OFFERED | CONTRACT_ENFORCED | SERVICES_RESCHEDULED | ...
  submitted_at          TIMESTAMPTZ,                           -- NULL until submitted; idempotency guard for double-submit
  viewed_at             TIMESTAMPTZ,                           -- stamped on first token resolve (mirrors GET /pay handler)
  created_at            TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_dispute_intake_campaign
    FOREIGN KEY (campaign_id) REFERENCES mkt_campaigns_list(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_dispute_intake_token
  ON mkt_dispute_intake(access_token);
CREATE INDEX IF NOT EXISTS idx_dispute_intake_campaign
  ON mkt_dispute_intake(campaign_id);
CREATE INDEX IF NOT EXISTS idx_dispute_intake_tenant
  ON mkt_dispute_intake(tenant_id)
  WHERE tenant_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_dispute_intake_expires
  ON mkt_dispute_intake(expires_at)
  WHERE submitted_at IS NULL;                                  -- pending intakes for expiry sweep

-- ============================================================
-- STEP 3: Dispute attachments table (proof files)
-- ============================================================
-- Metadata for owner-uploaded proof (PDF/PNG/JPEG ≤10MB). The actual
-- storage backend is wired in S2; this table holds the file_url +
-- metadata. ON DELETE CASCADE so clearing an intake clears its files.

CREATE TABLE IF NOT EXISTS mkt_dispute_attachments (
  id                    VARCHAR(255)  PRIMARY KEY,             -- mdatt-{nanoid}
  dispute_intake_id     VARCHAR(255)  NOT NULL,
  file_url              VARCHAR(500)  NOT NULL,
  file_name             VARCHAR(255)  NOT NULL,
  file_type             VARCHAR(20)   NOT NULL,                -- 'pdf' | 'png' | 'jpeg'
  file_size             INT,                                   -- bytes (nullable until storage backend confirms)
  uploaded_at           TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_dispute_attach_intake
    FOREIGN KEY (dispute_intake_id) REFERENCES mkt_dispute_intake(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_dispute_attach_intake
  ON mkt_dispute_attachments(dispute_intake_id);

-- ============================================================
-- VERIFICATION (run manually after applying)
-- ============================================================
-- \d mkt_campaigns_list
--   -- confirm new column: campaign_category VARCHAR(30) DEFAULT 'review_management'
-- SELECT campaign_category, COUNT(*) FROM mkt_campaigns_list GROUP BY campaign_category;
--   -- expect 'review_management' only until recovery campaigns are created
--
-- \d mkt_dispute_intake
--   -- confirm columns + UNIQUE(campaign_id) + UNIQUE(access_token) + FK
-- \d mkt_dispute_attachments
--   -- confirm columns + FK to mkt_dispute_intake
--
-- ============================================================
-- ROLLBACK
-- ============================================================
-- DROP TABLE IF EXISTS mkt_dispute_attachments;
-- DROP TABLE IF EXISTS mkt_dispute_intake;
-- DROP INDEX IF EXISTS idx_mkt_campaigns_campaign_category;
-- ALTER TABLE mkt_campaigns_list DROP COLUMN IF EXISTS campaign_category;
