import {
  Check,
  Info,
  AlertCircle,
  XCircle,
  HelpCircle,
  Heart,
  Flame,
  Star,
  ShoppingCart,
  Truck,
  Shield,
  Zap,
  Lock,
  Mail,
  Phone,
  MapPin,
  Calendar,
  Clock,
  CreditCard,
  Gift,
  ThumbsUp,
  ThumbsDown,
  User,
  Users,
  Search,
  Menu,
  Home,
  Settings,
  Bell,
  Camera,
  Music,
  Play,
  Pause,
  Download,
  Upload,
  FileText,
  Link,
  ExternalLink,
  Trash2,
  Pencil,
  Plus,
  Minus,
  ArrowRight,
} from 'lucide-react';

export type IconComponent = React.ComponentType<{
  className?: string;
  size?: number;
  style?: React.CSSProperties;
}>;

export const ICON_OPTIONS = [
  { label: 'Check', value: 'check' },
  { label: 'Info', value: 'info' },
  { label: 'Alert Circle', value: 'alert-circle' },
  { label: 'X Circle', value: 'x-circle' },
  { label: 'Help', value: 'help' },
  { label: 'Heart', value: 'heart' },
  { label: 'Fire', value: 'fire' },
  { label: 'Star', value: 'star' },
  { label: 'Shopping Cart', value: 'shopping-cart' },
  { label: 'Truck', value: 'truck' },
  { label: 'Shield', value: 'shield' },
  { label: 'Zap', value: 'zap' },
  { label: 'Lock', value: 'lock' },
  { label: 'Mail', value: 'mail' },
  { label: 'Phone', value: 'phone' },
  { label: 'Map Pin', value: 'map-pin' },
  { label: 'Calendar', value: 'calendar' },
  { label: 'Clock', value: 'clock' },
  { label: 'Credit Card', value: 'credit-card' },
  { label: 'Gift', value: 'gift' },
  { label: 'Thumbs Up', value: 'thumbs-up' },
  { label: 'Thumbs Down', value: 'thumbs-down' },
  { label: 'User', value: 'user' },
  { label: 'Users', value: 'users' },
  { label: 'Search', value: 'search' },
  { label: 'Menu', value: 'menu' },
  { label: 'Home', value: 'home' },
  { label: 'Settings', value: 'settings' },
  { label: 'Bell', value: 'bell' },
  { label: 'Camera', value: 'camera' },
  { label: 'Music', value: 'music' },
  { label: 'Play', value: 'play' },
  { label: 'Pause', value: 'pause' },
  { label: 'Download', value: 'download' },
  { label: 'Upload', value: 'upload' },
  { label: 'File Text', value: 'file-text' },
  { label: 'Link', value: 'link' },
  { label: 'External Link', value: 'external-link' },
  { label: 'Trash', value: 'trash-2' },
  { label: 'Pencil', value: 'pencil' },
  { label: 'Plus', value: 'plus' },
  { label: 'Minus', value: 'minus' },
  { label: 'Arrow Right', value: 'arrow-right' },
];

const ICON_MAP: Record<string, IconComponent> = {
  check: Check,
  info: Info,
  'alert-circle': AlertCircle,
  'x-circle': XCircle,
  help: HelpCircle,
  heart: Heart,
  fire: Flame,
  star: Star,
  'shopping-cart': ShoppingCart,
  truck: Truck,
  shield: Shield,
  zap: Zap,
  lock: Lock,
  mail: Mail,
  phone: Phone,
  'map-pin': MapPin,
  calendar: Calendar,
  clock: Clock,
  'credit-card': CreditCard,
  gift: Gift,
  'thumbs-up': ThumbsUp,
  'thumbs-down': ThumbsDown,
  user: User,
  users: Users,
  search: Search,
  menu: Menu,
  home: Home,
  settings: Settings,
  bell: Bell,
  camera: Camera,
  music: Music,
  play: Play,
  pause: Pause,
  download: Download,
  upload: Upload,
  'file-text': FileText,
  link: Link,
  'external-link': ExternalLink,
  'trash-2': Trash2,
  pencil: Pencil,
  plus: Plus,
  minus: Minus,
  'arrow-right': ArrowRight,
};

export function getIcon(name: string): IconComponent {
  return ICON_MAP[name] || HelpCircle;
}
