name: CI

on:
  push:
    branches: ["spec-sync", "main"]
  pull_request:
    branches: ["spec-sync", "main"]

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10.18.3
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm -r typecheck || true

      - name: Lint
        run: pnpm -r lint || true

      - name: Run API unit tests (Vitest)
        run: pnpm -C apps/api test

  web-e2e:
    runs-on: ubuntu-latest
    needs: api-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10.18.3
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Build all
        run: pnpm -r build

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Start API server
        env:
          API_PORT: 4000
        run: |
          pnpm -C apps/api start &
          npx wait-on http://localhost:4000/health

      - name: Start Web server
        env:
          NEXT_PUBLIC_API_BASE_URL: http://localhost:4000
        run: |
          pnpm -C apps/web start &
          npx wait-on http://localhost:3000

      - name: Run Playwright E2E
        env:
          WEB_URL: http://localhost:3000
          API_URL: http://localhost:4000
          TEST_EMAIL: owner@demo.local
          TEST_PASSWORD: password123
          TEST_TENANT_ID: demo-tenant
        run: pnpm -C apps/web test:e2e
